apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketball-exercises-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketball-exercises
  template:
    metadata:
      labels:
        app: basketball-exercises
    spec:
      containers:
        - image: lgaljo/rt_basketball_exercises:latest
          name: basketball-exercises
          env:
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ella.db.elephantsql.com/rwhhuqvq
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: rwhhuqvq
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass-exercises
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8088
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
---

apiVersion: v1
kind: Service
metadata:
  name: basketball-exercises
spec:
  type: ClusterIP
  ports:
    - port: 8088
      protocol: TCP
      targetPort: server
  selector:
    app: basketball-exercises