kumuluzee:
  name: basketball-exercises
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8088
    http:
      port: 8088
  datasources:
    - jndi-name: jdbc/exercisesDS
      connection-url: jdbc:postgresql://ella.db.elephantsql.com/rwhhuqvq
      username: rwhhuqvq
      password: 0afaeQId8iArwQqqEWjgwjXNV-03SATA
      max-pool-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/exercisesDS
  metrics:
    web-instrumentation:
      - name: exercises-endpoint
        url-pattern: /v1/exercises/*
  cors-filter:
    servlet:
      allow-origin: "*"
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                          <Configuration name="comments">
                              <Appenders>
                                  <Console name="console" target="SYSTEM_OUT">
                                      <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                  </Console>
                                  <Socket name="logstash" host="906c451a-bc58-4cb6-8145-6a2d768e120b-ls.logit.io"
                                  port="26828" protocol="UDP">
                                      <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                  </Socket>
                              </Appenders>
                              <Loggers>
                                  <!-- Default logger -->
                                  <Root level="all">
                                      <AppenderRef ref="console" level="info" />
                                      <AppenderRef ref="logstash" level="info" />
                                  </Root>
                              </Loggers>
                          </Configuration>'
  rest-client:
    registrations:
      - class: exercises-api
        url: http://localhost:8088/v1
        read-timeout: 5000
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://52.224.131.132:2379
      username: rso_etcd
      password: RsoTeam1234password!
  discovery:
    #cluster:
    etcd:
      hosts: http://52.224.131.132:2379
      username: rso_etcd
      password: RsoTeam1234password!
    ttl: 100
    ping-interval: 5

rest-config:
  maintenance-mode: false
  api-token: htn12kss3